### ISSUE TITLE
How did you manage to get this result with the tray icons?

### ISSUE THREAD

**Issue by RyanOrigens** [shub39/dotfiles#1]
I suppose you're not utilizing the built-in tray icons feature since I can't find it anywhere in your config, and I cannot replicate it with the built-in tray icons on my own. How did you achieve this amazing result, making the tray icons finally look good?

**Comment by shub39** [comment]
sorry for late reply. I am using wlr/taskbar module in waybar/modules for the taskbar and thanks!
