### ISSUE TITLE
Waybar just disappeared 

### ISSUE THREAD

**Issue by Motohrust** [shub39/dotfiles#2]
I pressed some buttons (super and 2-3 more) and waybar died. It doesn't works after super-alt-w, only shows notification, I looked through all configs and bindings... Nothing helped. Could you help me please?
And thank you for gorgeous dotfies.
![IMG_20241211_103502_703](https://github.com/user-attachments/assets/4d97fe3d-96d5-41f4-8d1f-719646bd92ca)
Oh, yes, hyprpaper script doesn't work too, Idk why, it forced me to use another utility

**Comment by shub39** [comment]
well it happens sometimes but restarting fixes it, try launching it manually `waybar -c \*path to config*\ -s \*path to style.css*\` and the exact problem should show up. as for hyprpaper is the package installed?

**Comment by Motohrust** [comment]
Thank you, Im kinda stupid, wrote config not proper and it just updated after pressing buttons. Yes, hyprpaper is installed
